# Generated by Django 4.2.7 on 2023-11-21 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
